<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Agency;
use AppBundle\Entity\Instance;

/**
 * HostingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HostingRepository extends \Doctrine\ORM\EntityRepository{

    public function findAllCustomersLegrain(Agency $agency){

        $query = $this->createQueryBuilder('h')
            ->select('h')
            ->innerJoin('h.user','u')
            ->where('u.agency = :agency')
            ->orWhere('u.parent is null')
            ->setParameter('agency',$agency)
            ->getQuery()
            ->getResult();

        return $query;
    }
    public function findByAgency(Agency $agency){

        $query = $this->createQueryBuilder('h')
            ->select('h')
            ->innerJoin('h.user','u')
            ->where('u.agency = :agency')
            ->setParameter('agency',$agency)
            ->getQuery()
            ->getResult();

        return $query;
    }


    public function findByInstance(Instance $instance){
        $query = $this->createQueryBuilder('h')
            ->select('h')
            ->innerJoin('h.productHosting','p')
            ->where('p.instance = :instance')
            ->setParameter('instance',$instance)
            ->getQuery()
            ->getResult();

        return $query;
    }
}
