<?php

namespace AppBundle\Repository;

/**
 * NumberVhostsInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumberVhostsInstanceRepository extends \Doctrine\ORM\EntityRepository
{
}
