imports:
    - { resource: config.yml }
    - { resource: parameters_dev.yml }


framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            bubble: false
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_address: me@example.com

# be simple Configuration
#be_simple_soap:
#    cache:
#        type:     disk
#        lifetime: 86400
#        limit:    5


#    services:
#        GwiHostingApi:
#            namespace:     http://devapi.gwi-hosting.fr/ws/GwiHostingApi/1.0/
#            binding:       rpc-literal
#            resource:      "@AppBundle/Controller/GwiHostingController.php"
#            resource_type: annotation
#        GwiHostingSecurityApi:
#                    namespace:     http://devapi.gwi-hosting.fr/ws/GwiHostingSecurityApi/1.0/
#                    binding:       rpc-literal
#                    resource:      "@AppBundle/Controller/GwiHostingSecurityController.php"
#                    resource_type: annotation
#        GandiApi:
#                    namespace:     http://devapi.gwi-hosting.fr/ws/GandiApi/1.0/
#                    binding:       rpc-literal
#                    resource:      "@GandiBundle/Controller/GandiController.php"
#                    resource_type: annotation
#
