<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccountBalanceLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountBalanceLineRepository extends EntityRepository
{


    public function maxIdTransaction(){
        return $this->createQueryBuilder('u')
            ->where('MAX(u.idTransaction)')
            ->getQuery()->getResult();
    }
}
