<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccountBalanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountBalanceRepository extends EntityRepository
{
}
