<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CGURepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CGURepository extends EntityRepository
{
}
