<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstanceRepository extends EntityRepository
{

    public function findByAgency(Agency $agency){
        $query = $this->createQueryBuilder('i')
            ->select('i')
            ->innerJoin('i.user','u')
            ->where('u.agency = :agency')
            ->setParameter('agency',$agency)
            ->getQuery()
            ->getResult();

        return $query;
    }



    public function findByProductReferenceAndUser($reference,User $user){
        return $this->createQueryBuilder('i')
            ->select('i')
            ->innerJoin('i.product', 'p')
            ->where('p.reference = :reference')
            ->andWhere('i.user = :user')
            ->setParameters(array('reference' => $reference, 'user' => $user))
            ->orderBy('i.dateEnd')
            ->getQuery()
            ->getResult();
    }

}
