<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Config\Definition\Exception\Exception;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{

    public function findOneByTldAndCategory($tld,$category){
        if(substr($tld,0,1)=='.')$tld = substr($tld,1);

        $query = $this->createQueryBuilder('p')
            ->select('p')
            ->leftJoin('p.categories', 'c')
            ->addSelect('c');


        $query = $query->add('where', $query->expr()->in('c', ':c'))
            ->andWhere('p.features LIKE :tld')
            ->andWhere('p.active = :active')
            ->setParameters(array('c'=> $category,'tld'=>"%.".$tld.'"%','active'=>true))
            ->getQuery()
            ->getSingleResult()
            ;

        return $query;
    }


    public function findByCategoryAndActive($category,$active){
        $query = $this->createQueryBuilder('p')
            ->select('p')
            ->leftJoin('p.categories', 'c')
            ->addSelect('c');

        $query = $query->add('where', $query->expr()->in('c', ':c'))
            ->andWhere('p.active = :active')
            ->setParameters(array('c'=> $category,'active'=>$active))
            ->orderBy('p.order')
            ->getQuery()
            ->getResult();

        return $query;
    }

}
